<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lumina.SeedDev</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Lumina.Domain\Lumina.Domain.csproj" />
    <ProjectReference Include="..\..\src\Lumina.Application\Lumina.Application.csproj" />
    <ProjectReference Include="..\..\src\Lumina.Infrastructure\Lumina.Infrastructure.csproj" />
  </ItemGroup>
</Project>
